title: Rachid Reda DOKKAR # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data consultant at DXC Technology and Data Science graduate from the University Paris Cité. Computer Science engineer from École Nationale Supérieure d'Informatique ESI Alger with 12 months of professional experience in computer vision and machine learning. Seasoned participant in machine learning competitions on Zindi (https://zindi.africa/users/ridadokkar), specializing in data engineering and data science consulting.
  <br><br>
  Azure AZ-900 and AI-900 cloud certifications, Top 25% in my first school ESI.
  <br><br>
  <a href="https://www.linkedin.com/in/dokkarrachidreda/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
