title: Rachid Reda DOKKAR # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Student in M2 Machine learning for Data Science at the University Paris Cité, Computer engineer graduate from the École Nationale Supérieur d'Informatique ESI Alger. 12 months of professional experience : 6 months in computer vision, 6 months in machine learning and statistics, and more than 2 years in machine learning  competitions on Zindi(https://zindi.africa/users/ridadokkar)
  <br><br>
  Preparing for Azure AZ-900 and DP-900 cloud certifications, Top 25% in my first school ESI.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
